export const ATTENDANCE = [
  {
    UId: "18BCS6543",
    Code: "CSB-371",
    Title: "Information Security",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2t/IZhK//iPq7aBzSbwWvAUk=",
    Lec_Attd: 3,
    Lec_Delv: 3,
    Lec_Perc: 100,
    name: "JATIN SARDA",
    Prac_Attd: 0,
    Prac_Delv: 0,
    Prac_Perc: 0,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "3",
    Total_Delv: 3,
    Total_Perc: 100,
    colorcode: "Green",
    TotalPercentage: "100",
    EligibilityDelivered: "3",
    EligibilityPercentage: "100",
    EligibilityAttended: "3",
  },
  {
    UId: "18BCS6543",
    Code: "CSB-372",
    Title: "Information Security Lab",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2t6hUykH4lt1AdLNlns5d1SI=",
    Lec_Attd: 0,
    Lec_Delv: 0,
    Lec_Perc: 0,
    name: "JATIN SARDA",
    Prac_Attd: 2,
    Prac_Delv: 2,
    Prac_Perc: 100,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "2",
    Total_Delv: 2,
    Total_Perc: 100,
    colorcode: "Green",
    TotalPercentage: "100",
    EligibilityDelivered: "2",
    EligibilityPercentage: "100",
    EligibilityAttended: "2",
  },
  {
    UId: "18BCS6543",
    Code: "CSM-361",
    Title: "MOOCs-III",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2t3QOfKCWIWEu9MTFB0SD/zg=",
    Lec_Attd: 0,
    Lec_Delv: 0,
    Lec_Perc: 0,
    name: "JATIN SARDA",
    Prac_Attd: 8,
    Prac_Delv: 10,
    Prac_Perc: 0,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "8",
    Total_Delv: 10,
    Total_Perc: 80,
    colorcode: "Green",
    TotalPercentage: "0",
    EligibilityDelivered: "0",
    EligibilityPercentage: "0",
    EligibilityAttended: "0",
  },
  {
    UId: "18BCS6543",
    Code: "CSP-356",
    Title: "Technical Training",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2t3rNsc/qETagTRsN4gALIBo=",
    Lec_Attd: 0,
    Lec_Delv: 0,
    Lec_Perc: 0,
    name: "JATIN SARDA",
    Prac_Attd: 2,
    Prac_Delv: 2,
    Prac_Perc: 100,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "2",
    Total_Delv: 2,
    Total_Perc: 100,
    colorcode: "Green",
    TotalPercentage: "100",
    EligibilityDelivered: "2",
    EligibilityPercentage: "100",
    EligibilityAttended: "2",
  },
  {
    UId: "18BCS6543",
    Code: "CSP-358",
    Title: "Project Based Learning in Java Lab",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2t28miWWq2Mmqk53ypK+5Pv8=",
    Lec_Attd: 0,
    Lec_Delv: 0,
    Lec_Perc: 0,
    name: "JATIN SARDA",
    Prac_Attd: 4,
    Prac_Delv: 4,
    Prac_Perc: 100,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "4",
    Total_Delv: 4,
    Total_Perc: 100,
    colorcode: "Green",
    TotalPercentage: "100",
    EligibilityDelivered: "4",
    EligibilityPercentage: "100",
    EligibilityAttended: "4",
  },
  {
    UId: "18BCS6543",
    Code: "CSR-355",
    Title: "Project",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2t/pErUIlKUzLj69hLtg/ZJs=",
    Lec_Attd: 0,
    Lec_Delv: 0,
    Lec_Perc: 0,
    name: "JATIN SARDA",
    Prac_Attd: 2,
    Prac_Delv: 2,
    Prac_Perc: 100,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "2",
    Total_Delv: 2,
    Total_Perc: 100,
    colorcode: "Green",
    TotalPercentage: "100",
    EligibilityDelivered: "2",
    EligibilityPercentage: "100",
    EligibilityAttended: "2",
  },
  {
    UId: "18BCS6543",
    Code: "CST-352",
    Title: "THEORY OF COMPUTATION",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2t4rtkLTRKmpXjLge83ik4SE=",
    Lec_Attd: 4,
    Lec_Delv: 4,
    Lec_Perc: 100,
    name: "JATIN SARDA",
    Prac_Attd: 0,
    Prac_Delv: 0,
    Prac_Perc: 0,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "4",
    Total_Delv: 4,
    Total_Perc: 100,
    colorcode: "Green",
    TotalPercentage: "100",
    EligibilityDelivered: "4",
    EligibilityPercentage: "100",
    EligibilityAttended: "4",
  },
  {
    UId: "18BCS6543",
    Code: "CST-353",
    Title: "Mobile Application Development",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2tw+y4DHhV7PXXuxNcj/J99c=",
    Lec_Attd: 3,
    Lec_Delv: 3,
    Lec_Perc: 100,
    name: "JATIN SARDA",
    Prac_Attd: 0,
    Prac_Delv: 0,
    Prac_Perc: 0,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "3",
    Total_Delv: 3,
    Total_Perc: 100,
    colorcode: "Green",
    TotalPercentage: "100",
    EligibilityDelivered: "3",
    EligibilityPercentage: "100",
    EligibilityAttended: "3",
  },
  {
    UId: "18BCS6543",
    Code: "CST-358",
    Title: "Project Based Learning in Java",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2tz+K5SDnJTTPTIdrx7q6nnc=",
    Lec_Attd: 1,
    Lec_Delv: 2,
    Lec_Perc: 50,
    name: "JATIN SARDA",
    Prac_Attd: 0,
    Prac_Delv: 0,
    Prac_Perc: 0,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "1",
    Total_Delv: 2,
    Total_Perc: 50,
    colorcode: "Green",
    TotalPercentage: "50",
    EligibilityDelivered: "2",
    EligibilityPercentage: "50",
    EligibilityAttended: "1",
  },
  {
    UId: "18BCS6543",
    Code: "CST-365",
    Title: "NETWORK OPERATING SYSTEM",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2tw4DEw2ko7fvVEvsghqbYdY=",
    Lec_Attd: 5,
    Lec_Delv: 5,
    Lec_Perc: 100,
    name: "JATIN SARDA",
    Prac_Attd: 0,
    Prac_Delv: 0,
    Prac_Perc: 0,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "5",
    Total_Delv: 5,
    Total_Perc: 100,
    colorcode: "Green",
    TotalPercentage: "100",
    EligibilityDelivered: "5",
    EligibilityPercentage: "100",
    EligibilityAttended: "5",
  },
  {
    UId: "18BCS6543",
    Code: "TDY-351",
    Title: "Soft Skills",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2t/ydQJaHAvAZCJdrtgBWef0=",
    Lec_Attd: 0,
    Lec_Delv: 0,
    Lec_Perc: 0,
    name: "JATIN SARDA",
    Prac_Attd: 2,
    Prac_Delv: 2,
    Prac_Perc: 100,
    Trl_Attd: 0,
    Trl_Delv: 0,
    Trl_Perc: 0,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "2",
    Total_Delv: 2,
    Total_Perc: 100,
    colorcode: "Green",
    TotalPercentage: "100",
    EligibilityDelivered: "2",
    EligibilityPercentage: "100",
    EligibilityAttended: "2",
  },
  {
    UId: "18BCS6543",
    Code: "TDY-352",
    Title: "Aptitude",
    DutyLeave: 0,
    DutyLeave_N_P: 0,
    DutyLeave_Others: 0,
    MedicalLeave: 0,
    EncryptCode: "07qcQ6ZoIXTAzTGRuwv2t5+NaUDcuQixhk7MmqSW6jU=",
    Lec_Attd: 0,
    Lec_Delv: 0,
    Lec_Perc: 0,
    name: "JATIN SARDA",
    Prac_Attd: 0,
    Prac_Delv: 0,
    Prac_Perc: 0,
    Trl_Attd: 2,
    Trl_Delv: 2,
    Trl_Perc: 100,
    Semester: 6,
    StudentId: 165343,
    Total_Attd: "2",
    Total_Delv: 2,
    Total_Perc: 100,
    colorcode: "Green",
    TotalPercentage: "100",
    EligibilityDelivered: "2",
    EligibilityPercentage: "100",
    EligibilityAttended: "2",
  },
];
