export const MARKS = [
  {
    name: "DESIGN AND ANALYSIS OF ALGORITHMS (CST-302)",
    marks: [
      { element: "Assignment", total: "10", obtained: "8.7" },
      {
        element: "Attendance and Engagement Score on BB",
        total: "2",
        obtained: "2",
      },
      { element: "Mid-Semester Test-1", total: "40", obtained: "30" },
      { element: "Quiz", total: "4", obtained: "3.13" },
      { element: "Surprise Test", total: "12", obtained: "9.2" },
      { element: "Mid-Semester Test-2", total: "40", obtained: "40" },
    ],
  },
  {
    name: "Artificial Intelligence & Machine Learning (CST-303)",
    marks: [
      { element: "Assignment", total: "10", obtained: "8.83" },
      {
        element: "Attendance and Engagement Score on BB",
        total: "2",
        obtained: "2",
      },
      { element: "Mid-Semester Test-1", total: "40", obtained: "36" },
      { element: "Quiz", total: "4", obtained: "3.67" },
      { element: "Surprise Test", total: "12", obtained: "11.17" },
      { element: "Mid-Semester Test-2", total: "40", obtained: "34" },
    ],
  },
  {
    name: "Computer Graphics (CST-305)",
    marks: [
      { element: "Assignment", total: "10", obtained: "7.33" },
      {
        element: "Attendance and Engagement Score on BB",
        total: "2",
        obtained: "2",
      },
      { element: "Mid-Semester Test-1", total: "40", obtained: "39" },
      { element: "Quiz", total: "4", obtained: "4" },
      { element: "Surprise Test", total: "12", obtained: "8.75" },
      { element: "Mid-Semester Test-2", total: "40", obtained: "40" },
    ],
  },
  {
    name: "Software Testing & Quality Assurance (CST-311)",
    marks: [
      { element: "Assignment", total: "10", obtained: "8.17" },
      {
        element: "Attendance and Engagement Score on BB",
        total: "2",
        obtained: "2",
      },
      { element: "Mid-Semester Test-1", total: "40", obtained: "38.5" },
      { element: "Quiz", total: "4", obtained: "4" },
      { element: "Surprise Test", total: "12", obtained: "10.83" },
      { element: "Mid-Semester Test-2", total: "40", obtained: "40" },
    ],
  },
  {
    name: "Operating Systems (CST-328)",
    marks: [
      { element: "Assignment", total: "10", obtained: "9" },
      {
        element: "Attendance and Engagement Score on BB",
        total: "2",
        obtained: "2",
      },
      { element: "Mid-Semester Test-1", total: "40", obtained: "37" },
      { element: "Quiz", total: "4", obtained: "3.9" },
      { element: "Surprise Test", total: "12", obtained: "12" },
      { element: "Mid-Semester Test-2", total: "40", obtained: "38" },
    ],
  },
  {
    name: "Aptitude (TDY-302)",
    marks: [
      { element: "Assignment", total: "12", obtained: "11" },
      {
        element: "Attendance and Engagement Score on BB",
        total: "4",
        obtained: "4",
      },
      { element: "Mid-Semester Test-1", total: "40", obtained: "39.5" },
      { element: "Quiz", total: "6", obtained: "5.5" },
      { element: "Surprise Test", total: "12", obtained: "11.67" },
      { element: "Mid-Semester Test-2", total: "40", obtained: "32" },
    ],
  },
  {
    name: "Soft Skills (TDY-301)",
    marks: [
      { element: "Write X (Soft Skills)", total: "10", obtained: "7.67" },
      {
        element: "LIVE Assignment (Soft Skills)",
        total: "30",
        obtained: "22.13",
      },
      {
        element: "Presentation (Soft Skills)",
        total: "30",
        obtained: "22",
      },
      {
        element: "Attendance and Engagement Score on BB(Soft Skills)",
        total: "4",
        obtained: "4",
      },
      { element: "Quiz (Soft Skills)", total: "6", obtained: "5" },
    ],
  },
  {
    name: "Artificial Intelligence & Machine Learning Lab (CSP-303)",
    marks: [
      { element: "Experiment-1", total: "20", obtained: "17.5" },
      { element: "Experiment-2", total: "20", obtained: "14" },
      { element: "Experiment-3", total: "20", obtained: "13.5" },
      { element: "Experiment-4", total: "20", obtained: "17.5" },
      { element: "Experiment-5", total: "20", obtained: "17" },
      { element: "Experiment-6", total: "20", obtained: "18.5" },
      { element: "Experiment-7", total: "20", obtained: "18" },
      { element: "Experiment-8", total: "20", obtained: "18.5" },
      { element: "Experiment-9", total: "20", obtained: "18" },
      { element: "Experiment-10", total: "20", obtained: "18" },
      { element: "Mid-Term Test", total: "20", obtained: "16.5" },
      {
        element: "Discussion Forum / Short Assignment / Portfolio",
        total: "4",
        obtained: "3.5",
      },
      {
        element: "Attendance and BB Engagement Score",
        total: "4",
        obtained: "4",
      },
    ],
  },
  {
    name: "Computer Graphics Lab (CSP-305)",
    marks: [
      { element: "Experiment-1", total: "20", obtained: "16.5" },
      { element: "Experiment-2", total: "20", obtained: "18" },
      { element: "Experiment-3", total: "20", obtained: "18.5" },
      { element: "Experiment-4", total: "20", obtained: "17.5" },
      { element: "Experiment-5", total: "20", obtained: "18.5" },
      { element: "Experiment-6", total: "20", obtained: "18" },
      { element: "Experiment-7", total: "20", obtained: "18" },
      { element: "Experiment-8", total: "20", obtained: "19" },
      { element: "Experiment-9", total: "20", obtained: "17" },
      { element: "Experiment-10", total: "20", obtained: "18" },
      { element: "Mid-Term Test", total: "20", obtained: "16.5" },
      {
        element: "Discussion Forum / Short Assignment / Portfolio",
        total: "4",
        obtained: "3.5",
      },
      {
        element: "Attendance and BB Engagement Score",
        total: "4",
        obtained: "4",
      },
    ],
  },
  {
    name: "Design & Analysis of Algorithms Lab (CSP-309)",
    marks: [
      { element: "Experiment-1", total: "20", obtained: "15" },
      { element: "Experiment-2", total: "20", obtained: "15" },
      { element: "Experiment-3", total: "20", obtained: "17" },
      { element: "Experiment-4", total: "20", obtained: "16.5" },
      { element: "Experiment-5", total: "20", obtained: "15" },
      { element: "Experiment-6", total: "20", obtained: "16.5" },
      { element: "Experiment-7", total: "20", obtained: "18" },
      { element: "Experiment-8", total: "20", obtained: "18.5" },
      { element: "Experiment-9", total: "20", obtained: "19" },
      { element: "Experiment-10", total: "20", obtained: "18.5" },
      { element: "Mid-Term Test", total: "20", obtained: "19.5" },
      {
        element: "Discussion Forum / Short Assignment / Portfolio",
        total: "4",
        obtained: "3.8",
      },
      {
        element: "Attendance and BB Engagement Score",
        total: "4",
        obtained: "4",
      },
    ],
  },
  {
    name: "Operating Systems Lab (CSP-328)",
    marks: [
      { element: "Experiment-1", total: "20", obtained: "16" },
      { element: "Experiment-2", total: "20", obtained: "18" },
      { element: "Experiment-3", total: "20", obtained: "20" },
      { element: "Experiment-4", total: "20", obtained: "15" },
      { element: "Experiment-5", total: "20", obtained: "19" },
      { element: "Experiment-6", total: "20", obtained: "20" },
      { element: "Experiment-7", total: "20", obtained: "19" },
      { element: "Experiment-8", total: "20", obtained: "20" },
      { element: "Experiment-9", total: "20", obtained: "18" },
      { element: "Experiment-10", total: "20", obtained: "19" },
      { element: "Mid-Term Test", total: "20", obtained: "18.9" },
      {
        element: "Discussion Forum / Short Assignment / Portfolio",
        total: "4",
        obtained: "3.5",
      },
      {
        element: "Attendance and BB Engagement Score",
        total: "4",
        obtained: "4",
      },
    ],
  },
  {
    name: "Project (CSR-311)",
    marks: [{ element: "- Grade", total: "-", obtained: "B+" }],
  },
];
