export const TIMETABLE = [
  {
    Mon: {
      "10:00-10:45AM": {
        title: "PROJECT BASED LEARNING IN JAVA",
        type: "Lecture",
        group: "All",
        teacher: "Sumedha Arora",
      },
      "11:00-11:45AM": {
        title: "NETWORK OPERATING SYSTEM",
        type: "Lecture",
        group: "All",
        teacher: "Geet Kiran Kaur",
      },
      "12:00-12:45PM": {
        title: "THEORY OF COMPUTATION",
        type: "Lecture",
        group: "All",
        teacher: "Debmani Saha",
      },
      "1:45-2:30PM": {
        title: "PROJECT",
        type: "Practical",
        group: "A",
        teacher: "Puneet Kaur",
      },
      "2:45-3:30PM": null,
      "3:45-4:30PM": null,
      "1:00-1:45PM": null,
    },
    Tue: {
      "10:00-10:45AM": {
        title: "TECHNICAL TRAINING",
        type: "Practical",
        group: "A",
        teacher: "Debmani Saha",
      },
      "11:00-11:45AM": {
        title: "TECHNICAL TRAINING",
        type: "Practical",
        group: "A",
        teacher: "Debmani Saha",
      },
      "12:00-12:45PM": {
        title: "NETWORK OPERATING SYSTEM",
        type: "Lecture",
        group: "All",
        teacher: "Geet Kiran Kaur",
      },
      "1:45-2:30PM": null,
      "2:45-3:30PM": {
        title: "PROJECT BASED LEARNING IN JAVA LAB",
        type: "Practical",
        group: "A",
        teacher: "Navdeep Singh",
      },
      "3:45-4:30PM": {
        title: "PROJECT BASED LEARNING IN JAVA LAB",
        type: "Practical",
        group: "A",
        teacher: "Navdeep Singh",
      },
      "1:00-1:45PM": {
        title: "INFORMATION SECURITY",
        type: "Lecture",
        group: "All",
        teacher: "Saurabh Goel",
      },
    },
    Wed: {
      "10:00-10:45AM": {
        title: "APTITUDE",
        type: "Tutorial",
        group: "A",
        teacher: "Komalpreet Kaur",
      },
      "11:00-11:45AM": {
        title: "APTITUDE",
        type: "Tutorial",
        group: "A",
        teacher: "Komalpreet Kaur",
      },
      "12:00-12:45PM": {
        title: "THEORY OF COMPUTATION",
        type: "Lecture",
        group: "All",
        teacher: "Debmani Saha",
      },
      "1:45-2:30PM": null,
      "2:45-3:30PM": {
        title: "INFORMATION SECURITY LAB",
        type: "Practical",
        group: "A",
        teacher: "Saurabh Goel",
      },
      "3:45-4:30PM": {
        title: "INFORMATION SECURITY LAB",
        type: "Practical",
        group: "A",
        teacher: "Saurabh Goel",
      },
      "1:00-1:45PM": {
        title: "MOBILE APPLICATION DEVELOPMENT",
        type: "Lecture",
        group: "All",
        teacher: "Puneet Kaur",
      },
    },
    Thu: {
      "10:00-10:45AM": {
        title: "THEORY OF COMPUTATION",
        type: "Lecture",
        group: "All",
        teacher: "Debmani Saha",
      },
      "11:00-11:45AM": {
        title: "INFORMATION SECURITY",
        type: "Lecture",
        group: "All",
        teacher: "Saurabh Goel",
      },
      "12:00-12:45PM": {
        title: "PROJECT BASED LEARNING IN JAVA LAB",
        type: "Practical",
        group: "A",
        teacher: "Navdeep Singh",
      },
      "1:45-2:30PM": null,
      "2:45-3:30PM": {
        title: "NETWORK OPERATING SYSTEM",
        type: "Lecture",
        group: "All",
        teacher: "Geet Kiran Kaur",
      },
      "3:45-4:30PM": null,
      "1:00-1:45PM": {
        title: "PROJECT BASED LEARNING IN JAVA LAB",
        type: "Practical",
        group: "A",
        teacher: "Navdeep Singh",
      },
    },
    Fri: {
      "10:00-10:45AM": {
        title: "PROJECT BASED LEARNING IN JAVA",
        type: "Lecture",
        group: "All",
        teacher: "Sumedha Arora",
      },
      "11:00-11:45AM": {
        title: "MOBILE APPLICATION DEVELOPMENT",
        type: "Lecture",
        group: "All",
        teacher: "Puneet Kaur",
      },
      "12:00-12:45PM": {
        title: "MOOCS-III",
        type: "Practical",
        group: "A",
        teacher: null,
      },
      "1:45-2:30PM": {
        title: "SOFT SKILLS",
        type: "Practical",
        group: "A",
        teacher: "Kanchan Dhiman",
      },
      "2:45-3:30PM": {
        title: "SOFT SKILLS",
        type: "Practical",
        group: "A",
        teacher: "Kanchan Dhiman",
      },
      "3:45-4:30PM": null,
      "1:00-1:45PM": null,
    },
  },
];
