# Generated by Django 3.1.5 on 2021-01-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rep',
            field=models.IntegerField(default=0),
        ),
    ]
