# Generated by Django 3.1.5 on 2021-01-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pims', '0002_auto_20210127_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rep',
            field=models.FloatField(default=0.0),
        ),
    ]
